### ISSUE TITLE
Could not create required folders

### ISSUE THREAD

**Issue by ajlooney22** [Osaxely/mc_addons_manager#12]
When I try to import anything. I am prompted, “Could not create required folders. Please restart MC Addons Manager.” However when I restart the program or even my Xbox nothing changes. Note that I am using an Xbox Series X.

**Comment by Osaxely** [comment]
Hello, sorry for the late response
It's maybe a permission problem, I will investigate of what causing this issue after this update.

**Comment by Chronicoverride** [comment]
Hey @ajlooney22 have you tried the latest update? See if it works. Just make sure the addons you are importing are compatible with 1.16. Please let us know if you have any problems still and if so please link the packs that are an issue. If you get an error message, please attach the error. Thank you!
