### ISSUE TITLE
No mapping for Unicode character exists in the target multi-byte code page

### ISSUE THREAD

**Issue by ptolemybowman** [Osaxely/mc_addons_manager#18]
When i click on resource packs the error
No mapping for the Unicode character exists in the target multi-byte code page.
Comes up. But when i click ok it lets me see all the resource packs that i have previously downloaded and put in the game before this app was necessary. But then when i click import and i then click on the resource pack i want to import it will say it successfully imported it even though it is then no-where to be seen.

**Comment by Osaxely** [comment]
Hello, thanks for reporting !
The problem is that the app support only Unicode characters, so packs with special characters (like chinese, or maybe accents) will not work.
I'm investigating how to make the app support every characters type
