### ISSUE TITLE
The application called an interface that was marshalled for a different thread

### ISSUE THREAD

**Issue by sk-kimbo** [Osaxely/mc_addons_manager#19]
when i import an mcpack it says “The application called an interface that was marshalled for a different thread” is there any fix?

**Comment by Osaxely** [comment]
Hello, thank for reporting the issue
I knew that this issue was here, and I think I know what causes this, will fix in the next update 👍 
For now I'm rewriting the getting/import for signifiant speed, but a problem that I'm investigating to has caused a slow-down in the developement :(

**Comment by Chronicoverride** [comment]
@sk-kimbo Have you tried the latest update for the app? If not give it a shot. Let us know if you still have the same error or not :)
