### ISSUE TITLE
[BUG] MC Addon Manager Launches and Closes

### ISSUE THREAD

**Issue by sionnainne** [Osaxely/mc_addons_manager#27]
**Describe the bug**
Launching the app the chest splash screen appears and loads into the app and immediately closes.

**To Reproduce**
1. Go to games and apps on Xbox one
2. Click on mc adding manager icon, select B on controller
3. Black splash screen with chest appears
4. White screen appears with “No packs found” in center and “getting packs” in top left corner. Other menu items appear on screen but are unclickable.
5. 5. App closes within 5 seconds.

**Expected behavior**
The app to open and remain open to select a menu item.

**Screenshots (Optional)**

**Desktop (Optional):**
 - OS: Xbox One
 - Version 10.0.19041.5481

**Additional context**
#

https://user-images.githubusercontent.com/77032921/103718110-289c0600-4f94-11eb-8a6d-98c4775d5d6c.MOV

**Comment by Terminator11216** [comment]
It happened when I joined the beta.... before hand I didn't have any problems with the app

**Comment by colsternc101** [comment]
I'm also experiencing this issue, started this morning (noon est)

**Comment by Terminator11216** [comment]
> I'm also experiencing this issue, started this morning (noon est)

Glad it's not only me having the problem but wish it was fixed

**Comment by Terminator11216** [comment]
It happened when I started the beta

**Comment by Terminator11216** [comment]
So is it fixed?

**Comment by Aidan8890** [comment]
> So is it fixed?
> […](#)

No it’s not, don’t know why they closed it

**Comment by Osaxely** [comment]
Hello, it’s fixed internally, the fixed version will be available this day, that’s why I closed the issue :)

**Comment by Mafia0087** [comment]
Ok ty!

**Comment by Terminator11216** [comment]
Ya it’s fixed and I love you new look thanks for all your help

**Comment by SbxFlameZz** [comment]
I have the same problem

**Comment by Terminator11216** [comment]
I have no problem it’s fixed for me

**Comment by Mafia0087** [comment]
I still have a problem, but I’m on Xbox and haven’t received and update yet so idk

**Comment by Mafia0087** [comment]
Aaaaaah, okay makes sense. Thank you so much!

**Comment by Osaxely** [comment]
:)

Le lun. 18 janv. 2021 à 23:11, Mafia0087 <notifications@github.com> a
écrit :
