### ISSUE TITLE
[BUG] Full Problem Explained

### ISSUE THREAD

**Issue by Dylan789** [Osaxely/mc_addons_manager#31]
Hello, this is a full explanation of the new problem that everyone has been having with the most recent update.  First off, this new update to this already amazing application makes everything a lot more efficient, being able to take the resource and behavior packs from a single download.  I really appreciate that people have taken the time to make something like this to make minecraft a lot more enjoyable.  To start off: every addon that was installed prior to this update still works. I downloaded a mutant creature addon  just before the updated version and it worked great.  After this update, that same addon still works and I can play it.  The problem comes into play, with the new update, when you newly install an addon and start the game.  When the game is loading, it runs smoothly until it gets to the nether background.  At some point in the nether background screen, the game freezes and ultimately crashes.  This only happens when you download a new addon and launch the game.  An example is the game does not crash when I only have the previously installed mutant creature addon downloaded (mind you it was downloaded before the update to Mc Addon Manager).  But now with using the new updated Mc Addon Manager, any addon installed will crash your game at the nether screen.  I have tried multiple tests (such as trying more than one new addon, deleting all other addons and only having one downloaded, etc) but every single time it crashes with the new addon downloaded.  And while going back to the nether screen after previously crashing, it says “Global Resources were Reset”.  But it only shows this for a split second before crashing if you are trying to load with a new download.  I am happy to provide any further explanation if need be, thank you.

**Comment by Osaxely** [comment]
Hello, thank you very much for this explanation ! :) This is very useful because this allow me to target the problem.
Some persons told me the same thing, so it looks that the problem is on the new importation code, maybe when the app move the pack to the game folder

**Comment by Kindalyy** [comment]
I have the same issues but it doesn’t let me open Minecraft, I’m on Xbox

**Comment by Osaxely** [comment]
Hello, is MC Addons Manager crashing ? If no, delete all addons that you've imported with previous. If Minecraft still crash after that, delete all the worlds that you haven't created in Minecraft.
Then all will be good, and you'll be able to import again without crash :)
If MC Addons Manager crash, I'm currently working on a fix.

**Comment by Dylan789** [comment]
I meant to say the other day, with the most recent update Mc Addons Manager is fully working with much more convenience.  Thank you again for the consistent improvement!

**Comment by Chronicoverride** [comment]
As long as you guys have the latest update for the app it works fine :)
