### ISSUE TITLE
[BUG] Resource packs not located

### ISSUE THREAD

**Issue by MilesBailey1** [Osaxely/mc_addons_manager#33]
When I have looked at screenshots of this app I have seen at the top that it displays resource packs as a category at the top. When installing this app this doesn’t appear so I cannot add the pack to the game

**Comment by Osaxely** [comment]
Hello ! It's normal, you must import before categories are shown :)

Le mer. 13 janv. 2021 à 17:35, MilesBailey1 <notifications@github.com> a
écrit :
