### ISSUE TITLE
[BUG] breaks the whole game 

### ISSUE THREAD

**Issue by XVolstrikerX** [Osaxely/mc_addons_manager#35]
I was installing Addons for my Minecraft, I installed one and then it breaks the game, I can’t play it and it crashes everytime, please get this fix fast my Minecraft is broken, permanently

**Comment by Osaxely** [comment]
Hello, When MC Addons Manager will be fixed, you’ll have to delete the pack that caused Minecraft problems, it will fix the problem.

**Comment by XVolstrikerX** [comment]
Thanks you it’s fixed now, without this it would been broken forever, I want to thank you

**Comment by Osaxely** [comment]
Perfect ! I'm closing the issue.
