### ISSUE TITLE
[BUG] Crash at starting

### ISSUE THREAD

**Issue by MrcamRampage** [Osaxely/mc_addons_manager#37]
App no longer works at all
Yesterday I was getting some good skin packs. After I got my first one, I was going to do a second one and I couldn't. The app just wouldn't work. Like, the app would open, I could see "export" and the other options in the top right. It would say loading packs, then if would bring me to the home screen, not even an error screen. I uninstalled and reinstalled, turn off and on my xbox, unplugged my xbox and even restart my xbox, nothing works. Please help.

**To Reproduce**
1. Go to 'MC Addons Manager'
2. Click on 'MC Addons Manager'
3. Now just wait for the app to kick you out.
4. Then you are at the home screen without a error message.

**Expected behavior**
MC Addons Manager working as prompted.

**Comment by Chronicoverride** [comment]
Hey @MrcamRampage 
Could you please send the links for the packs that you tried. We need the one that worked and also the one that didn't work, and please specify which is which so that we can test it out. More than likely it is an issue with the pack. If you uninstall the one that didn't work in MC ADDONS MANAGER and try a different skin pack does it work? Give it a shot and let us know. But also send those links please.

**Comment by MrcamRampage** [comment]
Well, it wasn't that a link didn't work. I got a pack (which did work, i used it in game) and there was an update that I forgot to mention. The update completed and then the problem that I mentioned earlier started happening. The wasn't any links that didn't work.

**Comment by Chronicoverride** [comment]
Yes but you said the first pack worked fine. Then the app updated and you tried a second pack and that one didn't work and made the app crash. Can you send that link for the bad pack that made the app crash so that I can investigate further please?

**Comment by MrcamRampage** [comment]
No, no. I was going to try a second pack but when i tried to load up the applications, it would crash. I could not get the second pack. The second pack did not crash the app, the app would crash on startup. I could not use the app at all after the update.

**Comment by Osaxely** [comment]
Ok, thank you very much for this report. Was your pack a world or an
'addon' ?

Le jeu. 21 janv. 2021 à 22:24, MrcamRampage <notifications@github.com> a
écrit :

**Comment by MrcamRampage** [comment]
it was actually a skin pack

**Comment by Osaxely** [comment]
Ok, so it's maybe a problem of JSON. I'm seeing

**Comment by Chronicoverride** [comment]
Can you send the links for the skin packs @MrcamRampage so we can try to replicate the issue?

**Comment by MrcamRampage** [comment]
I cant find them but I know they were on mcpedl. The first one was a anime male skin pack and the one that i could not test was called like, casual skin pack or something like that.

**Comment by MrcamRampage** [comment]
I have an update!  So i decided to try and start it with a different account on the same console and it works with the second account. I even got a skin pack with the second account. It still does not work on my main account.

**Comment by MrcamRampage** [comment]
Another update! i fixed it. So basically, I removed my account the put it back on my xbox which fortunately fixed it! All though I would really like to see this glitch fixed asap!!! Thanks for all the help!

**Comment by Osaxely** [comment]
Perfect! :) I didn't publish an update in the last days, but maybe you didn't have the 1.5.5 on your release version.

**Comment by Osaxely** [comment]
I close your issue.
