### ISSUE TITLE
[BUG] Bad JSON parsing

### ISSUE THREAD

**Issue by Osaxely** [Osaxely/mc_addons_manager#38]
**Describe the bug**
MC Addons Manager crashes with the error 'Unexpected character encountered while parsing value: ? Path line 0 position 0'

**To Reproduce**
**Could not reproduce the issue.**

**Expected behavior**
Handle error while parsing. Show the pack, but inform the user that a pack looks corrupted. For that, MC Addons Manager must check that the JSON will be valid.

**Screenshots (Optional)**
No screenshots are required.

**Desktop (Optional):**
- Any platform (Xbox/Windows), latest version-build

**Additional context**
This bug was reported in AppCenter.

**Comment by Chronicoverride** [comment]
![PromoImage160_en](https://user-images.githubusercontent.com/65269683/112145532-dd67bb80-8bb0-11eb-98aa-295bb2131211.png)
This issue is fixed for the update coming out on Friday
