### ISSUE TITLE
Null strings may not be marshaled in WinRT arguments

### ISSUE THREAD

**Issue by Osaxely** [Osaxely/mc_addons_manager#4]
Problem when importing some mods :
- TFKPv10 (Addon)
- Potopo: Plushies

Reported first by ErraticJJ on Youtube.

**Comment by harrisonadams** [comment]
I have the same issue with everything I’m downloading

**Comment by Osaxely** [comment]
Ok, thank for reporting too 👍 I have rewritten the Import() function ;
- New import algorithm that use recursivity (So more speed)
- New verification algorithm (More flexible, and more speed)
- New query system, it uses windows query for more speed too.
Just two bugs to fix, and after a pull to the repository, it will be send to the store :)

**Comment by Osaxely** [comment]
The bug has been fixed, and the app will be updated tomorrow or in two days (it depends of certification time).
If this issue occurs again, please re-open it ! :)
