### ISSUE TITLE
[BUG] My issue is when i Launch app it crashes

### ISSUE THREAD

**Issue by bazbread** [Osaxely/mc_addons_manager#42]
**Describe the bug**
when I launch mc addons manager it loads and in the top write Connor it says getting packs then it crashes I tried installing and uninstalling it does not work I restarted my Xbox does not work I also play on the Xbox one sorry i also caint provide screen shot but ill see what i can do 

**To Reproduce**
1. Launch the application
2. Wait for some seconds
3. Crash

**Expected behavior**
The application must start correctly.

**Comment by Osaxely** [comment]
Hello ! Your problem was found and I will find a way to fix it. Thanks for reporting !

**Comment by Osaxely** [comment]
I'm closing the issue because it's duplicated. But if you want to follow the bug fix road, go [here](https://github.com/Osaxely/mc_addons_manager/issues/28) (Issue #28)
