### ISSUE TITLE
[FEATURE] Global Resources 

### ISSUE THREAD

**Issue by CoadyKidd** [Osaxely/mc_addons_manager#43]
Can you please if possible make it so the resource packs pop up in the global resources pack some packs need this to work and also i want to use a pack on servers thank you in advance

**Comment by Osaxely** [comment]
Hello ! I'm currently working on this :)
I have to test some things to check if all is good with this features before announce further informations.

**Comment by CoadyKidd** [comment]
Hi there is the feature in any beta modes of the app if so how do I go around signing up

**Comment by Osaxely** [comment]
Hello again !
I've seen your request, you will be added tomorrow to the beta !

**Comment by CoadyKidd** [comment]
Hi there how is this going atm? Have you've found a solution? I'm just being nosey is all

**Comment by Osaxely** [comment]
I just achieved to do that this morning, you can see the image on the Twitter account [here](https://twitter.com/MCAddonsManager/status/1358397261743616002)

**Comment by CoadyKidd** [comment]
Good job! how do i know if im in the beta?

**Comment by Osaxely** [comment]
Normally you have a mail from osaxely33@gmail.com, the title is "MC Addons Manager - Beta".
I'm planning to make beta access more easier :)

**Comment by CoadyKidd** [comment]
oh how long does it usually take to be whitelisted

**Comment by Osaxely** [comment]
It doesn't take very long, sometimes I forgot some people. If you haven't be added, can you tell me your Xbox mail adress ? :)

**Comment by CoadyKidd** [comment]
my email is coadyjac1@gmail.com

**Comment by Osaxely** [comment]
You have been added !

**Comment by CoadyKidd** [comment]
ty

**Comment by CoadyKidd** [comment]
im gonna close the issue because you have it accomplished
