### ISSUE TITLE
[FEATURE] Delete source file even if there is error

### ISSUE THREAD

**Issue by CoadyKidd** [Osaxely/mc_addons_manager#44]
Hi there again sorry for opening so many threads but there's a bug happening for me where I would install the mcworld Singularity Skyblock and a different pack idk what it was but I would import the pack and then it would pop up saying there was an error I press ok and the pack/world is downloaded but because the error message popped up I can't delete the source file is there anyway you could whether fix this or add a button that deletes source packs 
-Coady 
Ps tysm for the help

Edit: I'm not sure what label to add nor how to add labels

**Comment by Osaxely** [comment]
Hello, don't worry for labels, I will add appropriated labels.
Your request is more a feature than a bug, but it's a very good idea, I note this for the next update !

**Comment by CoadyKidd** [comment]
Hi there I don't know if I described it poorly or what happened but I meant there's an error that pops up but when you press ok the pack is imported anyway so it's kinda like a fake error in a way it's very strange have a good one

**Comment by Osaxely** [comment]
Hello ! What's the error ?

**Comment by CoadyKidd** [comment]
Hi there the error is:
Error 
The specified file name or path took too long or a component of the specified path is too long


(I didn't think it was taking too long at all personally 🤣🤣)
As I said I press ok and then the file is imported and I have no way to delete the source file

**Comment by Osaxely** [comment]
Hello, this will be fixed in the next update.

**Comment by CoadyKidd** [comment]
Ty
