### ISSUE TITLE
[BUG] My addon manager crashes as soon as the update packs load, help?

### ISSUE THREAD

**Issue by helpwhyduck** [Osaxely/mc_addons_manager#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots (Optional)**

**Desktop (Optional):**
 - OS: [e.g. Windows]
 - Version [e.g. 20H2 build 19042]

**Additional context**

**Comment by Osaxely** [comment]
Hello, this problem is in fixing and will be fixed in the next update

**Comment by Chronicoverride** [comment]
![PromoImage160_en](https://user-images.githubusercontent.com/65269683/112144896-118eac80-8bb0-11eb-88d0-c8f0523d775d.png)
In case you haven't seen the announcement yet, here it is! All known bugs are fixed and a bunch of new features coming this Friday. I will have a new video on my YouTube Channel on Friday as well to coincide with the app launch, showing you guys all the new features.

**Comment by Chronicoverride** [comment]
The new update is now available for download. It addresses all known issues. Please update your app and give it another shot.
