### ISSUE TITLE
[BUG] Packs won't install

### ISSUE THREAD

**Issue by remchuu** [Osaxely/mc_addons_manager#50]
Whenever I try to install certain packs the app starts the installation then refreshes and doesn't install the pack, this only happens with some packs, yet some other packs install perfectly fine.

**Comment by Osaxely** [comment]
Hello, this problem will be fixed in the next update!
The main problem is caused probably because your pack had a ".zip" file in. Now this is handled and zip files inside packs will be imported too.

**Comment by Chronicoverride** [comment]
![PromoImage160_en](https://user-images.githubusercontent.com/65269683/112144839-08054480-8bb0-11eb-8d9f-3c876bdaf1af.png)
In case you guys haven't seen the announcement yet, here it is! All known bugs are fixed and a bunch of new features coming this Friday. I will have a new video on my YouTube Channel on Friday as well to coincide with the app launch, showing you guys all the new features.

**Comment by Terminator11216** [comment]
What is your YouTube channel name

**Comment by Osaxely** [comment]
@Terminator11216 Here is the link of his YouTube channel : https://www.youtube.com/channel/UC8u2Cwa1tVrmiNxvEHDmMZQ
You will find a lot of useful videos about Minecraft addons :)

**Comment by Chronicoverride** [comment]
The new update is now available for download. It addresses all known issues. Please update your app and give it another shot.
