### ISSUE TITLE
[BUG] My mc addon keeps on crashing

### ISSUE THREAD

**Issue by angelloko1** [Osaxely/mc_addons_manager#51]
**Describe the bug**
Every time I click it it keep on crashing.
**To Reproduce**

**Expected behavior**

**Screenshots (Optional)**

**Desktop (Optional):**
 - OS: [e.g. Windows]
 - Version [e.g. 20H2 build 19042]

**Additional context**

**Comment by angelloko1** [comment]
@Osaxely

**Comment by Chronicoverride** [comment]
![PromoImage160_en](https://user-images.githubusercontent.com/65269683/112144749-fa4fbf00-8baf-11eb-8a8f-f142a5ed1e26.png)
In case you guys haven't seen the announcement yet, here it is! All known bugs are fixed and a bunch of new features coming this Friday. I will have a new video on my YouTube Channel on Friday as well to coincide with the app launch, showing you guys all the new features.

**Comment by Chronicoverride** [comment]
The new update is now available for download. It addresses all known issues. Please update your app and give it another shot.
