### ISSUE TITLE
[BUG] Crashing 

### ISSUE THREAD

**Issue by liquidlegend52** [Osaxely/mc_addons_manager#54]
**Describe the bug* hi there when I open the app on my Xbox one s the app crashes in 3 seconds off opening, I find it very weird as my other half and brother can open it perfectly but I cannot, it’s like it can’t read my storage or something 

**To Reproduce**

**Expected behavior**

**Screenshots (Optional)**

**Desktop (Optional):**
 - OS: [e.g. Windows]
 - Version [e.g. 20H2 build 19042]

**Additional context**

**Comment by Osaxely** [comment]
Hello, this bug will be fixed in the next update, we hope a release in the week.

**Comment by Chronicoverride** [comment]
![PromoImage160_en](https://user-images.githubusercontent.com/65269683/112144427-9927eb80-8baf-11eb-85e4-590a2e0e8671.png)
Update this Friday!

**Comment by Chronicoverride** [comment]
The new update is now available for download. It addresses all known issues. Please update your app and give it another shot.
