### ISSUE TITLE
[ISSUE] .MCADDONS wont import

### ISSUE THREAD

**Issue by CoadyKidd** [Osaxely/mc_addons_manager#57]
So i was trying to import the Origins Addon ( https://mcpedl.com/origins-addon/ ) and it wouldnty let me import it so i had to split them up then today i tried the EM Client ( https://emclient.ga/ ) and it did the same thing i was getting the error null = value or something like that

**Comment by CoadyKidd** [comment]
this issue is on the newest beta btw

**Comment by Osaxely** [comment]
Hello, don't worry, the beta doesn't have the latest release features for now :)
I have tried and both packs imported in the newer version that will come in a day or two.
The EM Client imports correctly but it's marked as invalid though.
![image](https://user-images.githubusercontent.com/59126998/112750042-712cf380-8fc6-11eb-91ba-103168efa15c.png)

**Comment by CoadyKidd** [comment]
What does an invalid pack mean?

**Comment by Osaxely** [comment]
Invalid pack means that the pack contains a bad manifest that is not guaranteed to be read in Minecraft. But it can be still imported and used :)

**Comment by CoadyKidd** [comment]
Oh ok is it that the anticheat thing I saw on twitter?

**Comment by Osaxely** [comment]
No, anticheat will be triggered only on cheat packs (XRay), invalid packs are just packs that cannot be parsed in MC Addons Manager :)

**Comment by Chronicoverride** [comment]
The new update is out. Should address all issues.
