### ISSUE TITLE
[BUG] Mc addons exits itself

### ISSUE THREAD

**Issue by Masterwink2** [Osaxely/mc_addons_manager#60]
Every time I go on to mc addons and press accept on terms and service it starts searching for packs but after a few seconds it shuts down the app, why is this?

also I have my files explorer which could be effecting mc addon and I do have a lot of downloads etc

**Comment by Masterwink2** [comment]
Sorry for the bad report I’ve just made this account and I’m clueless.

**Comment by Chronicoverride** [comment]
Hey @Masterwink2 we are aware of the issue. This is a duplicate ticket. Please refer to #59

**Comment by Chronicoverride** [comment]
The hotfix was submitted for this over the weekend. It just needs to pass Microsoft certification. We hope the update will be live tomorrow.
