### ISSUE TITLE
[BUG] Anti-cheat False Positives

### ISSUE THREAD

**Issue by Chronicoverride** [Osaxely/mc_addons_manager#62]
**Describe the bug**
Multiple different types of packs are being flagged as cheats when they are not. We are aware of this false positive issue. The anti-cheat system is still in its infancy.

 **### If you are experiencing an issue with a pack and the app is flagging it as a cheat and you know it is not, please provide the link for all affected packs in this ticket.**

**Comment by Chronicoverride** [comment]
The hotfix was submitted for this over the weekend. It just needs to pass Microsoft certification. We hope the update will be live tomorrow.

**Comment by Osaxely** [comment]
The update was released, this issue can be closed :)
