### ISSUE TITLE
[PROBLEM] Manager keeps crashing

### ISSUE THREAD

**Issue by jukedminecraft** [Osaxely/mc_addons_manager#63]
Hi! whenever i try to load into the manager, it starts saying getting packs, and then it immediately kicks me out a second later. I’ve tried resetting my xbox one and also going into the app multiple times. I’m very confused and also i promised my friends i would get a bunch of minecraft mods today. hopefully this can be fixed soon.

**To Reproduce**
1. click on the app
2. let it say getting packs
3. you should be kicked out right after

**Expected behavior**
App to load and work properly

**Desktop (Optional):**
 Xbox one (carbon black color)

**Additional context**
Please fix soon?

**Comment by Wagey** [comment]
I am having this same issue I would like to download a texture pack or 2 but I cannot due to this, it would be great if this issue could be fixed soon!

**Comment by jukedminecraft** [comment]
yeah honestly it’s been over a week so i don’t understand why it still isn’t working. Hopefully the creator can look at these so they can be fixed and i can download a mod i need

**Comment by Osaxely** [comment]
Hello, the issue is being fixed.
I'm sorry for the time it takes, but I didn't have much time this week. The update should be released Tuesday because Easter day will delay certification process.

**Comment by jukedminecraft** [comment]
okay! thank you so much!

**Comment by Osaxely** [comment]
You're welcome!

Le sam. 3 avr. 2021 à 16:19, jukedminecraft ***@***.***> a
écrit :

**Comment by Wagey** [comment]
That would be amazing thank you!

**Comment by Osaxely** [comment]
I sent the update on certification a few hours ago. As I said, it should be available on Tuesday because of Easter day.

**Comment by Wagey** [comment]
Ok thank you this is much appreciated.

**Comment by Wagey** [comment]
I hate to tell you this but I have a uninstalled the app multiple times now and the problem is still occurring

**Comment by Osaxely** [comment]
Hello, the update is still not released due to Easter (Microsoft certification team doesn't work on closed days).
The update should be released tomorrow.

**Comment by Wagey** [comment]
Oh ok, sorry!

**Comment by Osaxely** [comment]
Hello @Wagey, are you still experiencing crashes ? The update has been released a few hours ago. Please reinstall your app and let us know how it goes.

**Comment by Osaxely** [comment]
I'm closing the issue due to inactivity. If you have still issues, don't hesitate to create a new one ! :)
