### ISSUE TITLE
[BUG] My addon is not importing

### ISSUE THREAD

**Issue by ArrivedChain98** [Osaxely/mc_addons_manager#64]
**Description of the issue** [Modified by Osaxely]
The user is trying to import an addon from an external device, but the application is failing to.

**To Reproduce**
1. Go to import
2. Click on what you want to download
3. It does nothing except highlight it green

**Expected behavior**

**Screenshots (Optional)**

**Desktop (xbox one s):**
 - OS: [e.g. Windows]
 - Version [e.g. 20H2 build 19042]

**I haven't been able to download anything since this update. I loved the application before, but now it just seems more frustrating**

**THIS ISSUE SHOULD INCLUDE DETAILS. PLEASE ANSWER THE ABOVE QUESTIONS, ALL ARE NOT REQUIRED, BUT THE THREE FIRST QUESTIONS SHOULD CONTAINS AN ANSWER**

**Comment by Chronicoverride** [comment]
@ArrivedChain98 The app has nothing to do with downloading. You have to download the addons first using mcpedl and then use MC Addons Manager to import the addons.

**Comment by Chronicoverride** [comment]
If you are having trouble with importing addons please provide links to the specific addons you are having trouble with and provided more details as to what happens when you import them.

**Comment by Osaxely** [comment]
I'm closing this issue.
Reason : Issues should detail what issue was encountered.

**Comment by ArrivedChain98** [comment]
I was trying to buy I was trying to download it off my flash drive

**Comment by Osaxely** [comment]
If I understand your issue, you tried to import a pack from an external storage device ?

**Comment by ArrivedChain98** [comment]
Yes sir. I've been doing it this way because my search engine doesn't quite
work well on my xbox. It's been working marvelously before the update and
now it won't download a single thing

**Comment by Osaxely** [comment]
Do you get any error when importing your addon ?

**Comment by ArrivedChain98** [comment]
I have never had a error pop up in the past, and of course anything to try
helping.

This is the link
SalvageRP_1616232918.mcpack

This is the page for it
https://mcpedl.com/salvage-addon/

**Comment by Osaxely** [comment]
I have just tried your pack and it worked on the latest hotfix that will arrive tomorrow. Here is the result :
![pack-success010](https://user-images.githubusercontent.com/59126998/113611805-4fc7a980-964f-11eb-8c5c-b561d8e8448f.png)
When the update will be released, I will answer to that issue. After the update, please let me know how it's going :)

**Comment by ArrivedChain98** [comment]
Alright. Thank you so much and have a great day

**Comment by Osaxely** [comment]
Hello @ArrivedChain98, the update has been released a few hours ago, could you reinstall the app and test ? Please let us know how it goes :)

**Comment by ArrivedChain98** [comment]
Sorry to tell you this, but its still not working. Now it's reading with a
error message say Error central Directory corrupt.

**Comment by ArrivedChain98** [comment]
One moment please. I believe this may be on my side. I don't know how but
through this whole ordeal I believe my files became corrupted somehow. I'm
going to try redownloading these then try importanting them again

**Comment by ArrivedChain98** [comment]
I'm glad I caught that. Sorry if I worried you, but everything is working
smoothly now. Thank you so much and keep up the amazing work. I think I can
speak for all us MC players when I say you have created something truly
amazing, and thanks for maintaining it. I hope you have a great day, and
good luck in your studies

**Comment by Osaxely** [comment]
you're welcome ! Thank you very much for having reported the issue :)

>

**Comment by Osaxely** [comment]
I'm closing the issue since it is solved. If anyone encounter any other issue, don't hesitate to create a new one :)

**Comment by ArrivedChain98** [comment]
Alright. I'll keep a eye out for you. Thanks for your hard work. Have a
blessed day

**Comment by Osaxely** [comment]
Thanks you too :)
