### ISSUE TITLE
[BUG] My Addons manager crashes immediately once I open it

### ISSUE THREAD

**Issue by kaiden43** [Osaxely/mc_addons_manager#65]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots (Optional)**

**Desktop (Optional):**
 - OS: [e.g. Windows]
 - Version [e.g. 20H2 build 19042]

**Additional context**

**Comment by Chronicoverride** [comment]
@kaiden43 
We are aware of the crashing issue. This is a duplicate ticket. Please see #59 
The hotfix was submitted over the weekend, it just has to pass Microsoft certification. We hope it will be live tomorrow.
