### ISSUE TITLE
New update bug report

### ISSUE THREAD

**Issue by ArrivedChain98** [Osaxely/mc_addons_manager#67]
I've found a bug in the new update. It starts up perfectly fine with all mods, but when I go to import ,and click on the mod to install it. It crashes.... I restart it and nothing was download. These files are all .zip by the way

_Originally posted by @ArrivedChain98 in https://github.com/Osaxely/mc_addons_manager/issues/28#issuecomment-813511611_

**Comment by Osaxely** [comment]
Hello, this issue is known and is being fixed in the next update that will normally arrive tomorrow. If you still encounter issues after, don't hesitate to let us know :)
