### ISSUE TITLE
[BUG] Resource pack crash

### ISSUE THREAD

**Issue by Danielking3432** [Osaxely/mc_addons_manager#71]
**Description**
I can not make a texture pack a global resource pack. The app crashes as a few seconds after i push global resources.

**To Reproduce**
1. Click on texture pack
2. Click global resource 

**Expected behavior**
I expected th app to load the pack and the global resource to be applied.

**Screenshots (Optional)**
Not available 

**Desktop (Optional):**
 Xbox 1s all digital 

**Additional context**

**Comment by Osaxely** [comment]
Hello, don't worry I'm aware of this issue and it's already fixed :) The update will arrive Monday during the day. But just to be sure, what's the pack you're trying to make global ?

**Comment by Danielking3432** [comment]
> Hello, don't worry I'm aware of this issue and it's already fixed :) The update will arrive Monday during the day. But just to be sure, what's the pack you're trying to make global ?

I am trying to use the utopia 16 team termite revamp

**Comment by Osaxely** [comment]
Ok thanks ! We'll test your pack. All should be fixed for you on monday! You'll be informed when the update will be released.

**Comment by Danielking3432** [comment]
> Ok thanks ! We'll test your pack. All should be fixed for you on monday! You'll be informed when the update will be released.

Ok, thank you

**Comment by Osaxely** [comment]
The update was delayed a little because a last minute bug was found and fixed. But it will be released before Wednesday :)

**Comment by Danielking3432** [comment]
> The update was delayed a little because a last minute bug was found and fixed. But it will be released before Wednesday :)

Hey, just got home to my mom's, was it released?

**Comment by Danielking3432** [comment]
> The update was delayed a little because a last minute bug was found and fixed. But it will be released before Wednesday :)

Seems to be fixed, thanks!

**Comment by Osaxely** [comment]
Nice! You're welcome:)
